# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- "**/*"

pr:
  branches:
    include:
    - '**/*' 

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Code Analyzer'
    organization: 'cascadian-aerial-robotics'
    scannerMode: 'MSBuild'
    projectKey: 'cascadian-aerial-robotics'
    projectName: 'main-website'

- task: PowerShell@2
  inputs:
    filePath: 'build/build.ps1'
    arguments: '$(Build.SourcesDirectory) $(Build.ArtifactStagingDirectory)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'